### ISSUE TITLE
[BUG] 2.13in V4 display not drawing properly

### ISSUE THREAD

**Issue by xslendix** [jayofelony/pwnagotchi#36]
**Describe the bug**
The display is not drawing properly. The display hardware is fine, checked with official waveshare demo.
**To Reproduce**
1. Connect waveshare V4 display
2. Flash image with ws4 display in it
3. dafaq?????

**Expected behavior**
The stuff to be drawn properly
**Screenshots**
![image](https://github.com/jayofelony/pwnagotchi-bookworm/assets/32436619/6594ce61-7a92-4d29-8f9f-c1bb660aabca)

**Environment (please complete the following information):**
 - Latest release at time of issue
 - RPi Zero 2 W

**Comment by jayofelony** [comment]
Can you show me your config.toml `ui.display` part?

**Comment by xslendix** [comment]
```toml
ui.display.enabled = true
ui.display.type = "waveshare_4"
ui.display.color = "black"
```

also tried color white and waveshare_3
